package com.smartcharity.model.subdoc;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class NgoReport {
    private String rawText;           // Original technical report text [cite: 30]
    private List<String> aiSummary;    // 3-bullet points generated by Gemini [cite: 35]
    private LocalDateTime uploadedAt;  // Timestamp for the impact feed [cite: 52]
}