spring.application.name=smartcharity-backend

spring.data.mongodb.uri=mongodb+srv://pranavharad:Pran%40122005@cluster0.tdesuri.mongodb.net/smartcharity=Cluster0
server.port=9090

gemini.api.key=AIzaSyCBwf2Bxf290uwN67QiLfM4hT4NvzZqfeI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta

jwt.secret=YourSuperSecretKeyHere_MakeItLong
jwt.expiration=86400000