package com.smartcharity.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Data
@Document(collection = "missions")
public class Mission {
    @Id
    private String id;
    private String title;
    private String description; // AI-generated by Gemini [cite: 146]
    private String ngoId;
    private double targetAmount;
    private double currentAmount;
    private int pointBonus;
    private LocalDateTime deadline;
    private List<String> joinedUserIds = new ArrayList<>();
}
